{{- $ref := dict "root" . "name" "topic-operator" "component" "device-registry" -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: topic-operator
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
