{{- $ref := dict
  "root" .
  "name" "mqtt-integration"
  "component" "integrations"
  "app" .Values.integrations.mqtt
  "transport" "mqtt"
  "metrics" true
-}}
{{- include "drogue-cloud-core.deployment.mqtt-integration" $ref -}}
