{{- $ref := dict
  "root" .
  "name" "mqtt-integration"
  "component" "integrations"
  "insecure" .Values.integrations.mqtt.insecure
  "app" .Values.integrations.mqtt
  "transport" "mqtt"
-}}
{{- include "drogue-cloud-core.deployment.mqtt-integration" $ref -}}
