{{- $ref := dict
  "root" .
  "name" "mqtt-integration-ws-browser"
  "component" "integrations"
  "app" .Values.integrations.mqttWsBrowser
  "transport" "websocket"
  "disableClientCertificates" true
  "metrics" true
-}}
{{- include "drogue-cloud-core.deployment.mqtt-integration" $ref -}}