{{- $ref := dict "root" . "name" "mqtt-integration" "component" "integrations" -}}
{{ if eq .Values.global.cluster "openshift"}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mqtt-integration
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}

spec:
  to:
    kind: Service
    name: mqtt-integration
  port:
    targetPort: service
  tls:
    termination: passthrough
{{- end }}