{{ $ref := dict "root" . "name" "mqtt-integration-ws" "component" "integrations" }}
kind: Service
apiVersion: v1
metadata:
  name: mqtt-integration-ws
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  selector:
    {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 4 }}

  {{- if eq .Values.global.cluster "openshift" }}
  type: ClusterIP
  {{- else if has .Values.global.cluster (list "minikube" "kind" ) }}
  type: NodePort
  {{- else }}
  type: LoadBalancer
  {{- end }}

  ports:
    - name: service
      protocol: TCP
      port: 1883
      targetPort: service
      {{- if has .Values.global.cluster (list "minikube" "kind" ) }}
      nodePort: {{ .Values.integrations.mqttWs.ingress.port }}
      {{- end }}