{{- if .Values.prometheus.podMonitors.enabled }}
{{- $ref := dict "root" . "name" "drogue-pod-monitor" "component" "metrics" -}}
kind: PodMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: drogue-pod-monitor
  labels:
    {{- include "drogue-cloud-metrics.labels" $ref | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 6 }}
  podMetricsEndpoints:
      - port: health
        path: /metrics
        scheme: http
        {{- with .Values.prometheus.server.global.scrape_interval }}
        interval: {{ . | quote }}
        {{- end }}
{{- end }}