{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/component: metrics
  name: drogue-iot-grafana-datasource
type: Opaque
stringData:
  prometheus-datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: drogue_metrics
      version: 1
      type: prometheus
      access: proxy
      orgId: 1
      uid: PCF44A6F8518AA255
      url: {{ .Values.grafana.datasource.url | quote }}
      basicAuth: false
      isDefault: false
      editable: false
      jsonData:
        tlsSkipVerify: {{ .Values.grafana.datasource.tlsSkipVerify }}
    {{- with .Values.grafana.datasource.customQueryParameters }}
        customQueryParameters: {{ . | quote}}
    {{ end }}
    {{- with .Values.grafana.datasource.httpMethod }}
        httpMethod: {{ . | quote }}
    {{ end }}
    {{- if .Values.grafana.datasource.token }}
        httpHeaderName1: "Authorization"
      secureJsonData:
        httpHeaderValue1: {{ ( printf "Bearer %s" .Values.grafana.datasource.token ) | quote }}
    {{ end }}
{{- end }}