{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/component: metrics
  name: drogue-iot-grafana-datasource
type: Opaque
stringData:
  prometheus-datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: drogue_metrics
      version: 1
      type: prometheus
      access: proxy
      orgId: 1
      url: {{ .Values.prometheus.url | quote }}
      basicAuth: false
      isDefault: true
      editable: false
{{ if .Values.prometheus.token }}
      jsonData:
        httpHeaderName1: "Authorization"
      secretJsonData:
        httpHeaderValue2: {{ printf "Bearer: " .Values.prometheus.token | quote }}
{{ end }}
{{- end }}
