{{- if and (.Values.pusher.enabled) (not .Values.pusher.knative) -}}
kind: Service
apiVersion: v1
metadata:
  labels:
    app: timescaledb-pusher
  name: timescaledb-pusher
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
  selector:
    app: timescaledb-pusher
{{- end -}}
