{{- if not .Values.kafka.external.enabled -}}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: drogue-iot
  labels:
    strimzi.io/cluster: drogue-iot
    {{- include "drogue-cloud-core.labels" (dict "root" . "name" "drogue-iot" "component" "kafka") | nindent 4 }}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls: []
{{- end }}
