{{- if not .Values.kafka.external.enabled -}}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Values.kafka.internalUserName }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterResourceName }}
    {{- include "drogue-cloud-core.labels" (dict "root" . "name" .Values.kafka.internalUserName "component" "kafka") | nindent 4 }}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls: []
{{- end }}
