{{- if not .Values.kafka.external.enabled -}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: iot-commands
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterResourceName }}
    {{- include "drogue-cloud-core.labels" (dict "root" . "name" "iot-commands" "component" "kafka") | nindent 4 }}
spec:
  config: {}
  partitions: 3
  replicas: 1
  topicName: iot-commands
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: registry
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterResourceName }}
    {{- include "drogue-cloud-core.labels" (dict "root" . "name" "registry" "component" "kafka") | nindent 4 }}
spec:
  config: {}
  partitions: 3
  replicas: 1
  topicName: registry
{{- end }}
