{{- $ref := dict "root" . "name" "websocket-integration" "component" "integrations" -}}
{{ if eq .Values.global.cluster "openshift"}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: websocket-integration
  annotations:
    {{- include "drogue-cloud-core.ingress.annotations" (dict "root" . "app" .Values.integrations.websocket ) | nindent 4 }}
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}

spec:
  {{- include "drogue-cloud-core.ingress.className" ( dict "root" . "ingress" .Values.integrations.websocket.ingress ) | nindent 2 }}
  rules:
    - host: {{ include "drogue-cloud-core.console.host" . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: websocket-integration
                port:
                  name: service
{{- end }}