{{- $ref := dict "root" . "name" "websocket-integration" "component" "integrations" -}}
{{ if eq .Values.global.cluster "openshift"}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: websocket-integration
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}

spec:
  host: {{ include "drogue-cloud-common.ingress.host" (dict "root" . "prefix" "websocket-integration" "ingress" .Values.integrations.websocket.ingress ) }}
  to:
    kind: Service
    name: websocket-integration
  port:
    targetPort: service
  tls:
    termination: passthrough
{{- end }}