{{- $ref := dict "root" . "name" "user-auth-service" "component" "device-registry" "metrics" true -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: user-auth-service
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"postgres"}]'
    {{- include "drogue-cloud-common.jaeger-annotations" . | nindent 4 }}
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}

spec:

  replicas: 1

  selector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 6 }}

  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        {{- include "drogue-cloud-core.labels" $ref | nindent 8 }}

    spec:
      initContainers:
        {{- include "drogue-cloud-common.init-container.wait-for-client-secret" ( dict "root" . "volume" "client-secret-services")  | nindent 8 }}
      containers:
        - name: service
          image: {{ include "drogue-cloud-common.image" $ref | quote }}
          imagePullPolicy: {{ include "drogue-cloud-common.image-pull-policy" . }}
          env:
            {{- include "drogue-cloud-common.rust.logging" ( dict "root" . "app" .Values.services.userAuth ) | nindent 12 }}
            {{- include "drogue-cloud-common.jaeger-env" ( dict "root" . "app" .Values.services.userAuth ) | nindent 12 }}
            - name: BIND_ADDR
              value: 0.0.0.0:8080
            - name: HEALTH__BIND_ADDR
              value: "0.0.0.0:9090"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE__PG__HOST
              value: postgres
            - name: SERVICE__PG__DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: databaseName
            - name: SERVICE__PG__USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: admin.username
            - name: SERVICE__PG__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: admin.password
            {{- include "drogue-cloud-core.oauth2-authenticator.env-vars" ( dict "root" . "clients" ( list "services" ) ) | nindent 12 }}
            - name: KEYCLOAK__URL
              value: {{ include "drogue-cloud-common.keycloak.url" . | quote }}
            - name: KEYCLOAK__ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: sso-service-credentials
            - name: KEYCLOAK__ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: sso-service-credentials
            - name: "KEYCLOAK__TLS_INSECURE"
              value: {{ .Values.oauth2.tls.insecure | quote }}
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 9090
              path: /readiness
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 9090
              path: /liveness
          ports:
            - containerPort: 8080
              name: api
              protocol: TCP
            {{- include "drogue-cloud-core.health-container-port" . | nindent 12 }}

          {{- include "drogue-cloud-core.container-resources" ( dict "root" . "app" .Values.services.userAuth) | nindent 10 }}

          volumeMounts:
            {{- include "drogue-cloud-core.keycloak-volume-mounts" . | nindent 12 }}

      volumes:
        - name: client-secret-services
          secret:
            secretName: keycloak-client-secret-services

        {{- include "drogue-cloud-core.keycloak-volumes" . | nindent 8 }}