kind: Service
apiVersion: v1
metadata:
  name: user-auth-service
  labels:
    app.kubernetes.io/name: user-auth-service
    app.kubernetes.io/part-of: device-registry
spec:

  selector:
    app.kubernetes.io/name: user-auth-service
    app.kubernetes.io/part-of: device-registry

  type: ClusterIP

  ports:
    - name: api
      port: 80
      protocol: TCP
      targetPort: 8080
