{{- $ref := dict "root" . "name" "user-auth-service" "component" "device-registry" -}}
kind: Service
apiVersion: v1
metadata:
  name: user-auth-service
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}

spec:

  selector:
    {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 4 }}

  type: ClusterIP

  ports:
    - name: api
      port: 80
      protocol: TCP
      targetPort: 8080
