{{- $ref := dict "root" . "name" "user-auth-service" "component" "device-registry" -}}
{{- $app := dict "root" . "name" "user-auth-service" "app" .Values.services.userAuth -}}
kind: Service
apiVersion: v1
metadata:
  name: user-auth-service
  annotations:
    {{- if and ( not $app.app.service.insecure ) .Values.global.drogueCloud.useServiceCA }}
    service.beta.openshift.io/serving-cert-secret-name: {{ $app.name }}
    {{- end }}
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}

spec:

  selector:
    {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 4 }}

  type: ClusterIP

  ports:
    - name: service
      port: {{ include "drogue-cloud-core.http-service-port" $app }}
      protocol: TCP
      targetPort: service
