{{- $ref := dict "root" . "name" "outbox-controller" "component" "device-registry" "metrics" true  -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: outbox-controller
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"postgres"}]'
    {{- include "drogue-cloud-common.jaeger-annotations" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "drogue-cloud-core.labels" $ref | nindent 8 }}
    spec:
      containers:
        - name: service
          image: {{ include "drogue-cloud-common.image" $ref | quote }}
          imagePullPolicy: {{ include "drogue-cloud-common.image-pull-policy" . }}
          env:
            {{- include "drogue-cloud-common.rust.logging" ( dict "root" . "app" .Values.services.outbox)  | nindent 12 }}
            {{- include "drogue-cloud-common.jaeger-env" ( dict "root" . "app" .Values.services.outbox ) | nindent 12 }}
            - name: HEALTH__BIND_ADDR
              value: "0.0.0.0:9090"
            - name: PG__HOST
              value: postgres
            - name: PG__DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: databaseName
            - name: PG__USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: admin.username
            - name: PG__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: admin.password
            - name: KAFKA_SENDER__TOPIC
              value: registry
            - name: KAFKA_SENDER__QUEUE_TIMEOUT
              value: 15s
            - name: KAFKA_SENDER__BOOTSTRAP_SERVERS
              value: {{ include "drogue-cloud-common.kafka-bootstrap-server" . }}
            {{- include "drogue-cloud-common.kafka-properties" (dict "root" . "prefix" "KAFKA_SENDER__PROPERTIES__" ) | nindent 12 }}
            - name: KAFKA_SOURCE__TOPIC
              value: registry
            - name: KAFKA_SOURCE__CONSUMER_GROUP
              value: outbox-controller
            - name: KAFKA_SOURCE__BOOTSTRAP_SERVERS
              value: {{ include "drogue-cloud-common.kafka-bootstrap-server" . }}
            {{- include "drogue-cloud-common.kafka-properties" (dict "root" . "prefix" "KAFKA_SOURCE__PROPERTIES__" ) | nindent 12 }}
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 9090
              path: /readiness
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 9090
              path: /liveness
          ports:
            - containerPort: 8080
              name: api
              protocol: TCP
            {{- include "drogue-cloud-core.health-container-port" . | nindent 12 }}

          {{- include "drogue-cloud-core.container-resources" ( dict "root" . "app" .Values.services.outbox ) | nindent 10 }}
