{{- $ref := dict "root" . "name" "outbox-controller" "component" "device-registry" -}}
kind: Service
apiVersion: v1
metadata:
  name: outbox-controller
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  selector:
    {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 4 }}
  ports:
    - name: api
      port: 80
      protocol: TCP
      targetPort: api
  type: ClusterIP
