global:
  # cluster defines the cluster type
  cluster: kubernetes
  # domain defines the domain suffix
  domain: .my-cluster.dns
  # instance is the ID of the installation
  instance: drogue

console:
  # allow overriding certain aspects of the console
  overrides:
    api: {}
      # url: https://foo-bar
    console: {}
      # url: https://foo-bar
    coapEndpoint: {}
      # url: coap://foo-bar
    httpEndpoint: {}
      # url: https://foo-bar
    mqttEndpoint: {}
      # port: 8883
    mqttIntegration: {}
      # port: 8883
    wsIntegration: {}
      # url: wss://foo-bar
    kafka: {}
      # servers: bootstrap:1234

endpoints:

  http:
    insecure: false
    ingress:
      port: 443

  mqtt:
    ingress:
      port: 8883

  coap:
    insecure: true
    ingress:
      port: 5683


integrations:

  mqtt:
    ingress:
      port: 8883

  websocket:
    insecure: false
    ingress:
      port: 443


services:
  console:
    ingress: {}
  api:
    ingress: {}
  sso:
    ingress: {}

defaults:
  images:
    repository: ghcr.io/drogue-iot
    # pullPolicy Sets the pull policy explicitly. Defaults to Always when using the 'latest'
    #   tag and to IfNotPresent otherwise.
    # pullPolicy: IfNotPresent
    # tag The container tag to apply. Defaults to the chart's application version
    # tag: latest

helper:
  image: registry.access.redhat.com/ubi8-minimal:latest

keycloak:
  adminPassword: admin123456
  identityProviders: []
  postgres:
    # mode is the way postgres gets configured. This can be:
    #  - drogue: Re-use the Drogue Cloud postgres instance
    #  - operator: Let the keycloak operate manage one
    #  - external: Use an external instance
    mode: drogue  # reuse drogue instance
    # username: foo
    # password: bar
    # you can provide either:
    #   url: jdbc:postgresql://foo/bar
    # or:
    #   host: postgres
    #   port: 5678
    #   databaseName: keycloak
  # resources can be used to define the resource requirements
  # resources:
  # postInstall is used to create a job which fixes up roles for a newly deployed Keycloak 15.x instance.
  postInstall:
    # enabled can be used to disable the job, in case you don't need it or are upgrading from
    # a Keycloak 12 instance, in which case you need to manually configure the roles.
    enabled: true
    image: quay.io/keycloak/keycloak:15.0.1

postgres:
  databaseName: registry
  username: admin
  password: admin123456
  podSecurityContext:
    enabled: false


kafka:

  version: "2.8.0"
  logVersion: "2.8"

  podSecurityContext:
    enabled: false

  externalAccess:
    enabled: true
    port: 9094
    type: nodeport
    tls:
      enabled: true

  # external can be used to configure Drogue Cloud to use an external Kafka instance
  external:
    enabled: false
    # bootstrapServer lists the boostrap server
    # bootstrapServer: my-server:9002
    # tls defined if TLS should be used or not
    tls:
      enabled: true
    sasl:
      enabled: false
      mechanism: plain
      # username: my-user
      # password: my-password

    # properties allow you to provide arbitrary additional properties
    properties: {}

  kafka:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true

  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true

  topicOperator: {}
  userOperator: {}
  tlsSidecar: {}
