apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: commands-http
  labels:
    {{- include "drogue-cloud-core.labels" (dict "root" . "name" "commands-http" "component" "endpoints") | nindent 4 }}
spec:
  consumerGroup: commands-http
  bootstrapServers:
    - drogue-iot-kafka-bootstrap.{{ .Release.Namespace }}.svc.cluster.local.:9092
  topics:
    - iot-commands
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: http-command
    uri: /command-service
