{{- $ref := dict "root" . "name" "http-endpoint" "component" "endpoints" "metrics" true -}}
{{- $app := dict "root" . "app" .Values.endpoints.http -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: http-endpoint
  annotations:
    {{- include "drogue-cloud-common.jaeger-annotations" . | nindent 4 }}
  labels:
    client.oauth2.drogue.io/services: ""
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  replicas: {{ $app.app.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "drogue-cloud-core.labels" $ref | nindent 8 }}
      annotations:
        {{- include "drogue-cloud-common.prometheus-annotations" . | nindent 8 }}

    spec:
      containers:
        - name: endpoint
          image: {{ include "drogue-cloud-common.image" $ref | quote }}
          imagePullPolicy: {{ include "drogue-cloud-common.image-pull-policy" . }}
          env:
            {{- include "drogue-cloud-common.rust.logging" $app | nindent 12 }}
            {{- include "drogue-cloud-common.jaeger-env" $app | nindent 12 }}
            {{- include "drogue-cloud-common.http-service-env" $app | nindent 12 }}
            {{- include "drogue-cloud-common.health-env" $app | nindent 12 }}
            - name: INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: instance
            - name: AUTH__URL
              value: {{ include "drogue-cloud-core.service-url.auth-service" . }}
            - name: AUTH__CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_ID
            - name: AUTH__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_SECRET
            {{- include "drogue-cloud-common.oauth2-internal.env-vars" (dict "root" . "prefix" "AUTH__" ) | nindent 12 }}
            - name: COMMAND_SOURCE_KAFKA__TOPIC
              value: iot-commands
            - name: COMMAND_SOURCE_KAFKA__CONSUMER_GROUP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_COMMAND_CONFIG__BOOTSTRAP_SERVERS
              value: {{ include "drogue-cloud-common.kafka-bootstrap-server" . }}
            {{- include "drogue-cloud-common.kafka-properties" (dict "root" . "prefix" "KAFKA_COMMAND_CONFIG__PROPERTIES__" ) | nindent 12 }}
            - name: KAFKA_DOWNSTREAM_CONFIG__BOOTSTRAP_SERVERS
              value: {{ include "drogue-cloud-common.kafka-bootstrap-server" . }}
            {{- include "drogue-cloud-common.kafka-properties" (dict "root" . "prefix" "KAFKA_DOWNSTREAM_CONFIG__PROPERTIES__" ) | nindent 12 }}
            {{- include "drogue-cloud-common.env-vars-extras" $app | nindent 12 }}

          ports:
            {{- include "drogue-cloud-common.http-service-container-port" $app | nindent 12 }}
            {{- include "drogue-cloud-common.health-container-port" . | nindent 12 }}

          {{- include "drogue-cloud-common.health-probes" $app | nindent 10 }}
          {{- include "drogue-cloud-common.container-resources" $app | nindent 10 }}

          volumeMounts:
          {{ if not .Values.endpoints.http.insecure }}
            - mountPath: /etc/tls/service
              name: service-tls
          {{ end }}

      volumes:

        {{ if not .Values.endpoints.http.service.insecure }}
        - name: service-tls
          secret:
            secretName: http-endpoint-tls
        {{ end }}

        - name: client-secret-services
          secret:
            secretName: keycloak-client-secret-services
