kind: Service
apiVersion: v1
metadata:
  name: http-endpoint
  labels:
    app.kubernetes.io/name: http-endpoint
    app.kubernetes.io/part-of: endpoints
spec:
  selector:
    app.kubernetes.io/name: http-endpoint
    app.kubernetes.io/part-of: endpoints

  {{- if eq .Values.global.cluster "openshift" }}
  type: ClusterIP
  {{- else if has .Values.global.cluster (list "minikube" "kind" ) }}
  type: NodePort
  {{- else }}
  type: LoadBalancer
  {{- end }}

  ports:
    - name: endpoint
      port: {{ if .Values.endpoints.http.insecure }}8080{{ else }}443{{ end }}
      protocol: TCP
      targetPort: endpoint
      {{- if has .Values.global.cluster (list "minikube" "kind" ) }}
      nodePort: {{ .Values.endpoints.http.ingress.port }}
      {{- end }}
