{{- $ref := dict "root" . "name" "http-endpoint" "component" "endpoints" -}}
{{- $app := dict "root" . "app" .Values.endpoints.http -}}
kind: Service
apiVersion: v1
metadata:
  name: http-endpoint
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  selector:
    {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 4 }}

  {{- if eq .Values.global.cluster "openshift" }}
  type: ClusterIP
  {{- else if has .Values.global.cluster (list "minikube" "kind" ) }}
  type: NodePort
  {{- else }}
  type: LoadBalancer
  {{- end }}

  ports:
    - name: service
      port: {{ include "drogue-cloud-common.http-service-port" $app }}
      protocol: TCP
      targetPort: service
      {{- if has .Values.global.cluster (list "minikube" "kind" ) }}
      nodePort: {{ .Values.endpoints.http.ingress.port }}
      {{- end }}
