apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: example-app
  labels:
    strimzi.io/cluster: drogue-iot
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
{{- range .Values.topics }}
      - resource:
          type: topic
          name: {{.}}
          patternType: literal
        operation: Read
        host: "*"
{{- end }}
