{{- if .Values.source.kafka.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: example-kafka-secret
  labels:
    app.kubernetes.io/name: example-kafka-secret
    app.kubernetes.io/part-of: example-app
data:
  {{- include "drogue-cloud-common.knative-kafka-net-secret-data" (dict "root" . "userName" "example-user") | nindent 2 }}
{{- end -}}
