apiVersion: v1
kind: Secret
metadata:
  name: example-kafka-secret
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: custom-app-1
data:
  {{- include "drogue-cloud-common.knative-kafka-net-secret-data" (dict "root" . "userName" "example-user") | nindent 2 }}
