apiVersion: v1
kind: Secret
metadata:
  name: external-kafka-secret
  labels:
    {{- include "drogue-cloud-core.labels" (dict "root" . "name" "external-kafka-secret" "component" "kafka") | nindent 4 }}
data:
  {{- include "drogue-cloud-common.knative-kafka-net-secret-data" . | nindent 2 }}
