{{- if .Values.kafka.external.enabled }}
{{- if .Values.kafka.external.sasl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: externa-kafka-secret
  labels:
    {{- include "drogue-cloud-core.labels" (dict "root" . "name" "externa-kafka-secret" "component" "kafka") | nindent 4 }}
data:
  {{- include "drogue-cloud-common.knative-kafka-net-secret-data" . | nindent 2 }}
{{- end}}
{{- end }}
