{{- if not .Values.kafka.external.enabled -}}
kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: drogue-iot
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    authorization:
      type: simple
      superUsers:
        - drogue-iot
    config:
      log.message.format.version: '2.7'
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
      - name: plain
        tls: false
        port: 9092
        type: internal
        authentication:
          type: scram-sha-512
      - name: tls
        tls: true
        port: 9093
        type: internal
        authentication:
          type: scram-sha-512
      - name: external
        tls: true
        port: 9094
        type: loadbalancer
        authentication:
          type: scram-sha-512
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
    version: 2.7.0
    template:
      pod:
        {{- if .Values.kafka.podSecurityContext.enabled }}
        securityContext: {{- omit .Values.kafka.podSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- else }}
        {}
        {{- end }}
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
    template:
      pod:
        {{- if .Values.kafka.podSecurityContext.enabled }}
        securityContext: {{- omit .Values.kafka.podSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- else }}
        {}
        {{- end }}
{{- end }}