{{- if include "drogue-cloud-core.cert-gen" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: certgen

rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "create", "patch" ]
{{- end }}
