{{- if .Values.ditto.metrics.enabled }}
{{- $ref := dict "root" . "name" "drogue-pod-monitor" "component" "metrics" -}}
kind: PodMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: ditto-pod-monitor
  labels:
    {{- include "drogue-cloud-twin.labels" $ref | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: ditto
      {{- include "drogue-cloud-common.healthSelector" . | nindent 6 }}
  podMetricsEndpoints:
      - port: metrics
        path: /
        scheme: http
        {{- with .Values.ditto.metrics.scrapeInterval }}
        interval: {{ . | quote }}
        {{- end }}
{{- end }}