{{- $ref := dict "root" . "name" "migrate-database" "component" "device-registry" -}}
kind: Job
apiVersion: batch/v1
metadata:
  name: migrate-database
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  backoffLimit: 1000
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: diesel-migrate
          image: {{ include "drogue-cloud-common.image" ( dict "root" . "name" "database-migration") | quote }}
          imagePullPolicy: {{ include "drogue-cloud-common.image-pull-policy" . }}
          env:
            {{- include "drogue-cloud-core.postgres.env-vars-default" . | nindent 12 }}
            # now we map that from our deadpool based configuration to diesel
            - name: DATABASE_URL
              value: postgres://$(PG__DB__USER):$(PG__DB__PASSWORD)@$(PG__DB__HOST):$(PG__DB__PORT)/$(PG__DB__DBNAME)
