{{- $ref := dict "root" . "name" "postgres-pvc" "component" "device-registry" -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: postgres-pvc
 labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
     storage: 1G
