{{- $ref := dict "root" . "name" "postgres-pvc" "component" "device-registry" -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size | quote }}
  {{- with .Values.postgres.storage.className }}
  storageClassName: {{ . | quote }}
  {{- end }}
