kind: Ditto
apiVersion: iot.eclipse.org/v1alpha1
metadata:
  name: ditto
  labels:
    app.kubernetes.io/name: ditto
spec:
  mongoDb:
    host: mongodb
    username:
      value: {{ index .Values.mongodb.auth.usernames 0 | quote }}
    password:
      value: {{ index .Values.mongodb.auth.passwords 0 | quote }}
    database:
      value: {{ index .Values.mongodb.auth.databases 0 | quote }}
  ingress:
    host: {{ include "drogue-cloud-common.ingress.host" (dict "root" . "prefix" "ditto" "ingress" .Values.ditto.ingress ) }}
