{{ if ne .Values.global.cluster "openshift" }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ditto
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ include "drogue-cloud-common.ingress.hostname" (list . "ditto" ) }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ditto-nginx
                port:
                  name: http
{{- end }}
