apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: digital-twin-kafka-source
  labels:
    app.kubernetes.io/part-of: digital-twin
spec:
  consumerGroup: digital-twin

  bootstrapServers:
    - {{ include "drogue-cloud-common.kafka-bootstrap-server" . }}

  topics:
      iot-events

  {{- include "drogue-cloud-common.knative-kafka-net" (dict "root" . "secretName" "external-kafka-secret" ) }}

  sink:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: digital-twin
