apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: digital-twin-kafka-source
  labels:
    app.kubernetes.io/part-of: digital-twin
spec:
  consumerGroup: digital-twin
  bootstrapServers:
    - drogue-iot-kafka-bootstrap:9092
  topics:
    - iot-events
  sink:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: digital-twin
