apiVersion: sources.knative.dev/{{ .Values.knative.kafkaSource.apiVersion }}
kind: KafkaSource
metadata:
  name: digital-twin
  labels:
    app.kubernetes.io/name: digital-twin
    app.kubernetes.io/part-of: digital-twin
spec:
  consumerGroup: digital-twin

  bootstrapServers:
    - {{ include "drogue-cloud-common.kafka-bootstrap-server" . }}

  topics:
    - {{ include "drogue-cloud-common.kafka-event-topic" (dict "application" .Values.drogueApplication ) }}

  {{- include "drogue-cloud-common.knative-kafka-net" (dict "root" . "secretName" "example-kafka-secret" "userName" "example-user" ) }}

  sink:
    uri: http://ditto:ditto@ditto-nginx.drogue-iot.svc.cluster.local:8080/api/2/cloudevents
