{{- $ref := dict "root" . "name" "doppelgaenger-swaggerui" "component" "digital-twin" "metrics" true  -}}
{{- $app := dict "root" . "name" "doppelgaenger-swaggerui" "app" .Values.services.swaggerUi -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: doppelgaenger-swaggerui
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"postgres"}]'
    {{- include "drogue-cloud-common.jaeger-annotations" . | nindent 4 }}
  labels:
    {{- include "drogue-cloud-twin.labels" $ref | nindent 4 }}

spec:

  replicas: {{ $app.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "drogue-cloud-twin.labels" $ref | nindent 8 }}
    spec:
      containers:
        - name: endpoint
          image: {{ $app.deployment.image | default "docker.io/swaggerapi/swagger-ui:v4.14.0" }}
          imagePullPolicy: {{ $app.deployment.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: BASE_URL
              value: /
            - name: OAUTH2_REDIRECT_URL
              value: {{ include "drogue-cloud-twin.api.url" . }}/oauth2-redirect.html
            - name: VALIDATOR_URL
              value: none
            - name: URL
              value: {{ include "drogue-cloud-twin.api.url" . | quote }}
            - name: OAUTH_CLIENT_ID
              value: api
            - name: OAUTH_SCOPES
              value: openid
            - name: OAUTH_ADDITIONAL_PARAMS
              value: '{nonce: "1"}'
          ports:
            - containerPort: 8080
              name: service
              protocol: TCP

          {{- include "drogue-cloud-common.container-resources" $app | nindent 10 }}

          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 8080
              path: /
