{{- $ref := dict "root" . "name" "doppelgaenger-swaggerui" "component" "digital-twin" "metrics" true  -}}
{{- $app := dict "root" . "name" "doppelgaenger-swaggerui" "app" .Values.services.swaggerUi -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: doppelgaenger-swaggerui
  annotations:
    io.drogue/tls-entrypoint-hash: {{ include (print $.Template.BasePath "/services/swaggerui/tls.yaml") . | sha256sum }}
  labels:
    {{- include "drogue-cloud-twin.labels" $ref | nindent 4 }}

spec:

  replicas: {{ $app.app.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "drogue-cloud-twin.labels" $ref | nindent 8 }}

    spec:
      containers:
        - name: endpoint
          image: {{ $app.app.deployment.image | default "docker.io/swaggerapi/swagger-ui:v4.14.0" }}
          imagePullPolicy: {{ $app.app.deployment.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: BASE_URL
              value: /
            - name: OAUTH2_REDIRECT_URL
              value: {{ include "drogue-cloud-twin.api.url" . }}/oauth2-redirect.html
            - name: VALIDATOR_URL
              value: none
            - name: URL
              value: {{ include "drogue-cloud-twin.api.url" . }}/api
            - name: OAUTH_CLIENT_ID
              value: api
            - name: OAUTH_SCOPES
              value: openid
            - name: OAUTH_ADDITIONAL_PARAMS
              value: '{nonce: "1"}'
            - name: PORT
              value: {{ include "drogue-cloud-common.http-bind-port" $app | quote }}

{{- if not $app.app.service.insecure }}
            - name: TLS_CERT_BUNDLE_FILE
              value: /etc/tls/service/tls.crt
            - name: TLS_KEY_FILE
              value: /etc/tls/service/tls.key
{{- end }}

          ports:
            - containerPort: {{ include "drogue-cloud-common.http-bind-port" $app }}
              name: service
              protocol: TCP

          {{- include "drogue-cloud-common.container-resources" $app | nindent 10 }}

          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: {{ include "drogue-cloud-common.http-bind-port" $app }}
              path: /
{{- if $app.app.service.insecure }}
              scheme: HTTP
{{- else }}
              scheme: HTTPS
{{- end }}

          volumeMounts:
            {{- include "drogue-cloud-common.tls-volume-mounts" $app | nindent 12 }}
            - name: tls-entrypoint
              mountPath: /docker-entrypoint.d/50-tls.sh
              subPath: 50-tls.sh
              readOnly: true

      volumes:
        {{- include "drogue-cloud-common.tls-volumes" $app | nindent 8 }}
        - name: tls-entrypoint
          configMap:
            name: doppelgaenger-swaggerui-entrypoint-tls
            defaultMode: 0555
