{{- $ref := dict "root" . "name" "doppelgaenger-swaggerui" "component" "digital-twin" -}}
{{- $app := dict "root" . "name" "doppelgaenger-swaggerui" "app" .Values.services.swaggerUi -}}
kind: Service
apiVersion: v1
metadata:
  name: doppelgaenger-swaggerui
  annotations:
    {{- include "drogue-cloud-common.tls-service-annotations" $app | nindent 4 }}
  labels:
    {{- include "drogue-cloud-twin.labels" $ref | nindent 4 }}

spec:

  selector:
    {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 4 }}

  type: ClusterIP

  ports:
    - name: service
      port: {{ include "drogue-cloud-common.http-service-port" $app }}
      protocol: TCP
      targetPort: service
