{{- $ref := dict
  "root" .
  "name" "mqtt-endpoint"
  "component" "endpoints"
  "app" .Values.endpoints.mqtt
  "transport" "mqtt"
  "metrics" true
-}}
{{- include "drogue-cloud-core.deployment.mqtt-endpoint" $ref -}}
