{{- $ref := dict
  "root" .
  "name" "mqtt-endpoint"
  "component" "endpoints"
  "insecure" .Values.endpoints.mqtt.insecure
  "app" .Values.endpoints.mqtt
  "transport" "mqtt"
-}}
{{- include "drogue-cloud-core.deployment.mqtt-endpoint" $ref -}}