{{- $ref := dict
  "root" .
  "name" "mqtt-endpoint-ws"
  "component" "endpoints"
  "insecure" .Values.endpoints.mqttWs.insecure
  "app" .Values.endpoints.mqttWs
  "transport" "websocket"
  "metrics" true
-}}
{{- include "drogue-cloud-core.deployment.mqtt-endpoint" $ref -}}