{{- $ref := dict "root" . "name" "mqtt-endpoint" "component" "endpoints" -}}
{{ if eq .Values.global.cluster "openshift" }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mqtt-endpoint
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  host: {{ include "drogue-cloud-common.ingress.host" (dict "root" . "prefix" "mqtt-endpoint" "ingress" .Values.endpoints.mqtt.ingress ) }}
  to:
    kind: Service
    name: mqtt-endpoint
  port:
    targetPort: endpoint
  tls:
    termination: passthrough
{{- end }}
