{{- $ref := dict "root" . "name" "mqtt-endpoint-ws" "component" "endpoints" -}}
kind: Service
apiVersion: v1
metadata:
  name: mqtt-endpoint-ws
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  selector:
    {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 4 }}

  {{- if eq .Values.global.cluster "openshift" }}
  type: ClusterIP
  {{- else if has .Values.global.cluster (list "minikube" "kind" ) }}
  type: NodePort
  {{- else }}
  type: LoadBalancer
  {{- end }}

  ports:
    - name: endpoint
      protocol: TCP
      port: 1883
      targetPort: endpoint
      {{- if has .Values.global.cluster (list "minikube" "kind" ) }}
      nodePort: {{ .Values.endpoints.mqttWs.ingress.port }}
      {{- end }}