{{ if .Values.postgres.enabled }}

{{- $ref := dict "root" . "name" "postgres-pvc" "component" "digital-twin" -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  labels:
    {{- include "drogue-cloud-twin.labels" $ref | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size | quote }}
  {{- with .Values.postgres.storage.className }}
  storageClassName: {{ . | quote }}
  {{- end }}

{{- end }}