{{- $ref := dict "root" . "name" "api" "component" "api" -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: api
  annotations:
    {{- include "drogue-cloud-common.ingress.annotations" (dict "root" . "app" .Values.services.api ) | nindent 4 }}
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  {{- include "drogue-cloud-common.ingress.className" ( dict "root" . "ingress" .Values.services.api.ingress) | nindent 2 }}
  rules:
    - host: {{ include "drogue-cloud-core.api.host" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console-backend
                port:
                  name: service
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: console-backend
                port:
                  name: service
          - path: /.well-known/
            pathType: Prefix
            backend:
              service:
                name: console-backend
                port:
                  name: service
          - path: /api/console/
            pathType: Prefix
            backend:
              service:
                name: console-backend
                port:
                  name: service
          - path: /api/tokens/
            pathType: Prefix
            backend:
              service:
                name: console-backend
                port:
                  name: service
          - path: /api/admin/v1alpha1/user
            pathType: Prefix
            backend:
              service:
                name: console-backend
                port:
                  name: service
          - path: /api/admin/v1alpha1/apps
            pathType: Prefix
            backend:
              service:
                name: device-management-service
                port:
                  name: service
          - path: /api/registry/
            pathType: Prefix
            backend:
              service:
                name: device-management-service
                port:
                  name: service
          - path: /api/command/
            pathType: Prefix
            backend:
              service:
                name: command-endpoint
                port:
                  name: service
