{{- $ref := dict "root" . "name" "command-endpoint" "component" "endpoints" -}}
{{- $app := dict "root" . "name" "command-endpoint" "app" .Values.services.command -}}
kind: Service
apiVersion: v1
metadata:
  name: command-endpoint
  annotations:
    {{- include "drogue-cloud-common.tls-service-annotations" $app | nindent 4 }}
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  selector:
    {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 4 }}

  type: ClusterIP

  ports:
    - name: service
      protocol: TCP
      port: {{ include "drogue-cloud-common.http-service-port" $app }}
      targetPort: service
