{{- $ref := dict "root" . "name" "coap-endpoint" "component" "endpoints" -}}
{{ if eq .Values.global.cluster "openshift" }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: coap-endpoint
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  to:
    kind: Service
    name: coap-endpoint
  port:
    targetPort: endpoint
  tls:
    termination: passthrough
{{- end }}
