---
kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-datasources
data:
  iot.yaml: |
    apiVersion: 1

    datasources:
      - name: IoT
        type: influxdb
        access: proxy
        database: $DS_DATABASE
        url: http://influxdb:8086
        user: $DS_USERNAME
        secureJsonData:
          password: $DS_PASSWORD
        editable: false
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-dashboard-providers
data:
  local.yaml: |
    apiVersion: 1

    providers:
      - name: configmap
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-dashboards
data:
  {{ range $path, $_ :=  .Files.Glob  "dashboards/*.json" }}
  {{ base $path }}: |
  {{- $.Files.Get $path | nindent 4 }}
  {{ end }}
