kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: grafana
  annotations:
    {{ if and ( eq .Values.global.cluster "openshift" ) ( not .Values.grafana.ingress.insecure )}}
    route.openshift.io/termination: "edge"
    {{- else }}
    kubernetes.io/ingress.class: "nginx"
    {{- end }}
spec:
  rules:
    - host: {{ include "drogue-cloud-common.ingress.host" (dict "root" . "prefix" "grafana" "ingress" .Values.grafana.ingress ) }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: web
