apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana

subjects:
  - kind: ServiceAccount
    name: grafana

roleRef:
  kind: Role
  name: grafana
  apiGroup: rbac.authorization.k8s.io
