apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client-grafana
  labels:
    app.kubernetes.io/part-of: console
spec:
  realmSelector:
    matchLabels:
      app.kubernetes.io/part-of: console
  client:
    clientId: grafana
    clientAuthenticatorType: client-secret
    enabled: true
    rootUrl: ""
    publicClient: false
    implicitFlowEnabled: false
    standardFlowEnabled: true
    serviceAccountsEnabled: false
    fullScopeAllowed: true
    redirectUris:
      - {{ include "drogue-cloud-common.ingress.proto" . -}}{{ include "drogue-cloud-common.ingress.hostname" ( list . "grafana" ) }}/login/generic_oauth
    defaultRoles:
      - "grafana-admin"
      - "grafana-editor"
    protocolMappers:
      - name: add-grafana-roles
        protocol: "openid-connect"
        protocolMapper: "oidc-usermodel-client-role-mapper"
        consentRequired: false
        config:
          multivalued: "true"
          userinfo.token.claim: "true"
          claim.name: "roles"
          jsonType.label: "String"
          usermodel.clientRoleMapping.clientId: "grafana"
