{{- if false }}

{{- if and .Values.grafana.keycloak.enabled .Values.grafana.keycloak.client.create }}
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client-grafana
  labels:
    app.kubernetes.io/name: client-grafana
    app.kubernetes.io/part-of: example-app
spec:
  realmSelector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" (dict "root" . "name" "drogue" "component" "sso") | nindent 6 }}
  roles:
    - name: "grafana-admin"
    - name: "grafana-editor"
  client:
    clientId: grafana
    clientAuthenticatorType: client-secret
    enabled: true
    rootUrl: ""
    publicClient: false
    implicitFlowEnabled: false
    standardFlowEnabled: true
    serviceAccountsEnabled: false
    fullScopeAllowed: false
    redirectUris:
      - {{ include "drogue-cloud-common.ingress.url" (dict "root" . "prefix" "grafana" "ingress" .Values.grafana.ingress ) }}/login/generic_oauth
    defaultClientScopes:
      - "email"
      - "profile"
      - "roles"
      - "web-origins"
    optionalClientScopes:
      - "address"
      - "microprofile-jwt"
      - "offline_access"
      - "phone"
    protocolMappers:
      - name: add-grafana-roles
        protocol: "openid-connect"
        protocolMapper: "oidc-usermodel-client-role-mapper"
        consentRequired: false
        config:
          multivalued: "true"
          userinfo.token.claim: "true"
          claim.name: "roles"
          jsonType.label: "String"
          usermodel.clientRoleMapping.clientId: "grafana"
{{- end }}

{{- end }}
