apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: timescaledb
  labels:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/part-of: custom-app-1
spec:
  consumerGroup: timescaledb

  bootstrapServers:
    - {{ include "drogue-cloud-common.kafka-bootstrap-server" . }}

  topics:
    {{ .Values.consumer.topics | toYaml | nindent 4 }}

  {{- include "drogue-cloud-common.knative-kafka-net" (dict "root" . "secretName" "example-kafka-secret" "userName" "example-user" ) }}

  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: timescaledb-pusher
