kind: Secret
apiVersion: v1
metadata:
  name: timescaledb-config
type: Opaque
data:
  read.username: {{ .Values.timescale.database.adminUser | b64enc }}
  read.password: {{ .Values.timescale.database.adminPassword | b64enc }}
