kind: Secret
apiVersion: v1
metadata:
  name: timescaledb-secret
type: Opaque
data:
  read.username: {{ .Values.timescale.database.readUser | b64enc }}
  read.password: {{ .Values.timescale.database.readPassword | b64enc }}
  admin.username: {{ .Values.timescale.database.adminUser | b64enc }}
  admin.password: {{ .Values.timescale.database.adminPassword | b64enc }}
