apiVersion: v2
name: drogue-cloud-metrics
description: Drogue IoT Cloud metrics stack installation
keywords:
  - IoT
home: https://drogue.io
icon: https://blog.drogue.io/favicon.svg

maintainers:
  - name: dejanb
    email: dbosanac@redhat.com

type: application

version: 0.6.0
appVersion: 0.10.0

kubeVersion: ">= 1.19.0"

dependencies:
  - name: drogue-cloud-common
    version: 0.6.0
    repository: file://../drogue-cloud-common
  - name: prometheus
    version: ~14.6.0
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.createInstance
  - name: grafana
    version: ~6.30.2
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
