prometheus:
  createInstance: true

  kubeStateMetrics:
    enabled: true

  podMonitors:
    enabled: false

  server:
    global:
      scrape_interval: 10s
    service:
      servicePort: 9090
    ingress:
      enabled: false

grafana:
  enabled: true
  adminPassword: admin123456

  grafana.ini:
    dashboards:
      default_home_dashboard_path: "/tmp/dashboards/drogue-dashboard.json"

  labels:
    app.kubernetes.io/component: metrics
  podLabels:
    app.kubernetes.io/component: metrics

  ingress:
    enabled: true

  datasource:
    url: http://drogue-iot-prometheus-server.drogue-iot:9090
    tlsSkipVerify: false
    # token: <bearer token>

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      enabled: true
      label: grafana_datasource
