prometheus:
  createInstance: true
  host:
  port:

  server:
    global:
      scrape_interval: 10s
    service:
      servicePort: 9090
    ingress:
      enabled: true

grafana:
  enabled: true
  adminPassword: admin123456

  labels:
    app.kubernetes.io/component: metrics
  podLabels:
    app.kubernetes.io/component: metrics

  ingress:
    enabled: true

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      enabled: true
      label: grafana_datasource
