{{- $ref := dict "root" . "name" "device-management-service" "component" "device-registry" -}}
{{- $app := dict "root" . "name" "device-management-service" "app" .Values.services.registry -}}
kind: Service
apiVersion: v1
metadata:
  name: device-management-service
  annotations:
    {{- include "drogue-cloud-core.tls-service-annotations" $app | nindent 4 }}
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}

spec:

  selector:
    {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 4 }}

  type: ClusterIP

  ports:
    - name: service
      port: {{ include "drogue-cloud-core.http-service-port" $app }}
      protocol: TCP
      targetPort: service
