{{- $ref := dict "root" . "name" "ditto" "component" "digital-twin" -}}
kind: Ditto
apiVersion: iot.eclipse.org/v1alpha1
metadata:
  name: ditto
  labels:
    {{- include "drogue-cloud-twin.labels" $ref | nindent 4 }}

spec:

  disableInfraProxy: true

  {{ with .Values.ditto.version }}version: {{ . | quote }}{{ end }}
  {{ with .Values.ditto.registry }}registry: {{ . | quote }}{{ end }}
  {{ with .Values.ditto.pullPolicy }}pullPolicy: {{ . | quote }}{{ end }}

  metrics:
    enabled: {{ .Values.ditto.metrics.enabled }}

  services:
    connectivity:
      replicas: {{ .Values.ditto.services.connectivity.replicas | default 1 }}
      logLevel: {{ .Values.ditto.services.connectivity.logLevel | default .Values.ditto.logLevel | default "info" | quote }}
    concierge:
      replicas: {{ .Values.ditto.services.concierge.replicas | default 1 }}
      logLevel: {{ .Values.ditto.services.concierge.logLevel | default .Values.ditto.logLevel | default "info" | quote }}
      additionalProperties:
        "ditto.concierge.enforcement.restrict-creation.grant.0.auth-subjects.0": "keycloak:drogue-admin"
    gateway:
      replicas: {{ .Values.ditto.services.gateway.replicas | default 1 }}
      logLevel: {{ .Values.ditto.services.gateway.logLevel | default .Values.ditto.logLevel | default "info" | quote }}
    policies:
      replicas: {{ .Values.ditto.services.policies.replicas | default 1 }}
      logLevel: {{ .Values.ditto.services.policies.logLevel | default .Values.ditto.logLevel | default "info" | quote }}
    things:
      replicas: {{ .Values.ditto.services.things.replicas | default 1 }}
      logLevel: {{ .Values.ditto.services.things.logLevel | default .Values.ditto.logLevel | default "info" | quote }}
    thingsSearch:
      replicas: {{ .Values.ditto.services.thingsSearch.replicas | default 1 }}
      logLevel: {{ .Values.ditto.services.thingsSearch.logLevel | default .Values.ditto.logLevel | default "info" | quote }}

  devops:
    password:
     value: {{ .Values.ditto.devops.password }}

  {{ with .Values.ditto.kafka }}
  kafka:
    {{- . | toYaml | nindent 4 }}
  {{ end }}

  {{ with .Values.ditto.mongoDb }}
  mongoDb:
    {{- . | toYaml | nindent 4 }}
  {{ else }}
  mongoDb:
    host: mongodb
    username:
      value: {{ index .Values.mongodb.auth.usernames 0 | quote }}
    password:
      value: {{ index .Values.mongodb.auth.passwords 0 | quote }}
    database:
      value: {{ index .Values.mongodb.auth.databases 0 | quote }}
  {{ end }}

  ingress:
    host: {{ include "drogue-cloud-common.ingress.host" (dict "root" . "prefix" "ditto" "ingress" .Values.ditto.ingress ) }}

  keycloak:
    url: {{ include "drogue-cloud-common.ingress.url" (dict "root" . "prefix" "sso" "ingress" .Values.sso.ingress ) }}
    redirectUrl: {{ include "drogue-cloud-common.ingress.url" (dict "root" . "prefix" "ditto" "ingress" .Values.ditto.ingress ) }}/oauth2/callback
    realm: {{ .Values.sso.realm | default "drogue" }}
    label: "Drogue Cloud"
    description: "Log in using Drogue Cloud"
    disableProxy: true

    {{- with .Values.sso.client }}
    clientId:
      {{ .id | nindent 6 }}
    clientSecret:
      {{ .secret | nindent 6 }}
    {{- else }}
    clientId:
      secret:
        name: keycloak-client-secret-ditto
        key: CLIENT_ID
    clientSecret:
      secret:
        name: keycloak-client-secret-ditto
        key: CLIENT_SECRET
    {{- end }}
