{{- $ref := dict "root" . "name" "demo-link-digital-twin" "component" "digital-twin" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-link-digital-twin
  labels:
    demo: ""
    {{- include "drogue-cloud-twin.labels" $ref | nindent 4 }}
data:
  href: {{ include "drogue-cloud-common.ingress.url" (dict "root" . "prefix" "ditto" "ingress" .Values.ditto.ingress ) }}
  label: Digital Twin
