apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: influxdb
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/part-of: custom-app-1
spec:
  consumerGroup: influxdb

  bootstrapServers:
    - {{ include "drogue-cloud-common.kafka-bootstrap-server" . }}

  topics:
    - events-example-app

  {{- include "drogue-cloud-common.knative-kafka-net" (dict "root" . "secretName" "external-kafka-secret" ) }}

  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: influxdb-pusher
