apiVersion: v2
name: drogue-cloud-common
description: Common functionality for Drogue Cloud charts
keywords:
  - IoT
home: https://drogue.io
icon: https://blog.drogue.io/favicon.svg

maintainers:
  - name: ctron
    email: ctron@dentrassi.de
    url: https://dentrassi.de

type: library

version: 0.7.0-alpha1
