global:
  # domain defines the domain suffix
  domain: .my-cluster.dns
  # cluster defines the cluster type
  cluster: kubernetes

  drogueCloud:
    jaeger: {}
    # if the openshift service CA is available and should be used
    useServiceCA: false
    keycloak:
      # enable keycloak deployment
      enabled: true
      # downgrade to insecure deployment
      insecure: false
      postInstall:
        image: quay.io/keycloak/keycloak:18.0.1
