kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-config
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: device-registry
data:
  databaseName: {{ .Values.postgres.databaseName }}
