{{- $ref := dict "root" . "name" "postgres-secret" "component" "device-registry" -}}
kind: Secret
apiVersion: v1
metadata:
  name: postgres-secret
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
type: Opaque
data:
  admin.username: {{ .Values.postgres.username | b64enc | quote }}
  admin.password: {{ .Values.postgres.password | b64enc | quote }}
