kind: Secret
apiVersion: v1
metadata:
  name: postgres-secret
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: device-registry
type: Opaque
data:
  admin.username: {{ .Values.postgres.username | b64enc | quote }}
  admin.password: {{ .Values.postgres.password | b64enc | quote }}
