---
kind: Secret
apiVersion: v1
metadata:
  name: keycloak-client-secret-api
  labels:
    {{- include "drogue-cloud-twin.labels" (dict "root" . "name" "keycloak-client-secret-api" "component" "sso") | nindent 4 }}
data:
  CLIENT_ID: {{ "api" | b64enc | quote }}
  CLIENT_SECRET: {{ "" | b64enc | quote }}
---
kind: Secret
apiVersion: v1
metadata:
  name: keycloak-client-secret-services
  labels:
    {{- include "drogue-cloud-twin.labels" (dict "root" . "name" "keycloak-client-secret-services" "component" "sso") | nindent 4 }}
data:
  CLIENT_ID: {{ "services" | b64enc | quote }}
  CLIENT_SECRET: {{ .Values.keycloak.clients.services.clientSecret | b64enc | quote }}
