{{- if .Values.keycloak.enabled }}

{{- /* Credentials for accessing the Keycloak API */}}
{{- /* By default, the same as the admin user */}}
apiVersion: v1
kind: Secret
metadata:
  name: sso-service-credentials
  labels:
    {{- include "drogue-cloud-twin.labels" (dict "root" . "name" "sso-service-credentials" "component" "sso") | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4= # admin
  password: {{ .Values.keycloak.adminPassword | b64enc }}

{{- end }}{{/* keycloak deployment enabled */}}