{
 "title": "Example Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "device_id",
    "label": "Device ID",
    "query": "select distinct device_id from temperatures"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  device_id AS metric,\n  avg(temperature) AS \"temperature\"\nFROM temperatures\nWHERE\n  $__timeFilter(\"time\") AND\n  device_id IN ($device_id)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  max(temperature) AS \"temperature\"\nFROM temperatures\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  device_id AS metric,\n  avg(humidity) AS \"humidity\"\nFROM temperatures\nWHERE\n  $__timeFilter(\"time\") AND\n  device_id IN ($device_id)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  max(humidity) AS \"humidity\"\nFROM temperatures\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  device_id AS metric,\n  avg(battery) AS \"battery\"\nFROM temperatures\nWHERE\n  $__timeFilter(\"time\") AND\n  device_id IN ($device_id)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT device_id as \"Device\", min(battery) as \"Battery Level\" FROM temperatures WHERE battery < 10 AND $__timeFilter(time) GROUP BY device_id ORDER BY 1,2;"
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 16 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  device_id,\n  temperature,\n  lat,\n  lon\nFROM temperatures\nWHERE\n  $__timeFilter(\"time\")\n  AND lat IS NOT NULL\n  AND lon IS NOT NULL\nORDER BY 1,2"
    }
   ]
  }
 ]
}