global:
  cluster: kubernetes
  domain: .my-cluster.dns

drogueApplication:
  name: example-app
  # eventTopic can provide an explicit event topic
  # eventTopic: <topic name>

kafka:
  external:
    enabled: false
    tls:
      enabled: false
    sasl:
      enabled: false
    bootstrapServers: my-bootstrap-server:9092

grafana:
  adminPassword: admin123456
  image: docker.io/grafana/grafana:8.0.6
  podSecurityContext:
    enabled: false
  ingress: {}

  keycloak:
    enabled: false
    ingress: {}
    realm: drogue
    client:
      # create can be used to deploy a keycloak client, works only when deployed alongside keycloak
      create: false
      # id contains the OAuth2 client ID
      # id: <id>
      # secret contains the optional OAuth2 client secret
      # secret: <secret>
      # kubernetesSecret allows to configure a secret that will contain the client secrets
      kubernetesSecret: keycloak-client-secret-grafana # kubernetes secret

timescale:
  database:
    image: docker.io/timescale/timescaledb-postgis:latest-pg12
    adminUser: admin
    adminPassword: admin123456
    name: example
  pusher:
    image: ghcr.io/drogue-iot/postgresql-pusher:0.1.0
