global:
  cluster: kubernetes
  domain: .my-cluster.dns

drogueApplication:
  name: drogue-public-temperature
  # eventTopic can provide an explicit event topic
  # eventTopic: <topic name>

# autoCreate controls the automatic creation of an application and device after the installation of the example
#
# Note that this will only work if the example is deployed next to the Drogue Core installation, as it needs access
# to the OAuth2 secret for the "services" client. Also will the process only to create the application and device.
# Disabling the process later, will neither delete the device nor the application.
autoCreate:
  # enabled it used to control the auto-creation process.
  enabled: false
  device:
    name: device1
    password: hey-rodney

knative:
  kafkaSource:
    apiVersion: v1beta1

kafka:
  external:
    enabled: false
    tls:
      enabled: false
    sasl:
      enabled: false
    bootstrapServers: my-bootstrap-server:9092

grafana:
  adminPassword: admin123456
  image: docker.io/grafana/grafana:8.5.2
  podSecurityContext:
    enabled: false
  ingress: {}

  keycloak:
    enabled: false
    ingress: {}
    realm: drogue
    client:
      # create can be used to deploy a keycloak client, works only when deployed alongside keycloak
      create: false
      # id contains the OAuth2 client ID, defaults to "grafana"
      # id: <id>
      # secret contains the optional OAuth2 client secret
      # secret: <secret>
      # kubernetesSecret allows to configure a secret that will contain the client secrets
      # kubernetesSecret: keycloak-client-secret-grafana  # kubernetes secret

timescale:
  database:
    image: docker.io/timescale/timescaledb-ha:pg14-ts2.6-latest
    adminUser: admin
    adminPassword: admin123456
    readUser: reader
    readPassword: reader1234
    name: example
  postInstall:
    image: docker.io/bitnami/postgresql:14

pusher:
  enabled: true
  knative: false
  image: ghcr.io/drogue-iot/postgresql-pusher:0.1.0

source:
  kafka:
    enabled: false
  drogue:
    enabled: true
    image: ghcr.io/drogue-iot/drogue-event-source:0.1.1
    endpoint: wss://ws-integration.sandbox.drogue.cloud
    # user: XXX
    # Create your token with `drg admin tokens create`
    # token: XXX
    sink: http://timescaledb-pusher:80
