global:
  cluster: kubernetes
  domain: .my-cluster.dns

grafana:
  adminPassword: admin123456
  podSecurityContext:
    enabled: false

kafka:
  external:
    enabled: false
    tls:
      enabled: false
    sasl:
      enabled: false
