global:
  cluster: kubernetes
  domain: .my-cluster.dns

grafana:
  adminPassword: admin123456
  image: docker.io/grafana/grafana:7.5.6
  podSecurityContext:
    enabled: false
  ingress: {}

kafka:
  external:
    enabled: false
    tls:
      enabled: false
    sasl:
      enabled: false

influx:
  database:
    image: docker.io/library/influxdb:1.8
  pusher:
    image: ghcr.io/drogue-iot/influxdb-pusher:0.5.0

services:
  sso:
    ingress: {}
