global:
  cluster: kubernetes
  domain: .my-cluster.dns

grafana:
  adminPassword: admin123456
  image: docker.io/grafana/grafana:8.0.6
  podSecurityContext:
    enabled: false
  ingress: {}

kafka:
  external:
    enabled: false
    tls:
      enabled: false
    sasl:
      enabled: false

timescale:
  database:
    image: docker.io/timescale/timescaledb-postgis:latest-pg12
    adminUser: admin
    adminPassword: admin123456
    name: example
  pusher:
    image: ghcr.io/drogue-iot/postgresql-pusher:0.1.0

services:
  sso:
    ingress: {}

consumer:
  topics:
    - events-example-app
  groups:
    - "*"
