{{- if .Values.autoCreate.enabled }}
{{ $ref := (dict "root" . "partOf" "deployment" "component" "post-install" "name" "post-install-data" ) }}
kind: Secret
apiVersion: v1
metadata:
  name: post-install-auto-create
  labels:
    {{- include "drogue-cloud-common.selectorLabels" $ref  | nindent 4 }}
type: Opaque
data:
  {{ $currentScope := . }}
  {{- range $path, $_ := .Files.Glob "scripts/auto-create/*" }}
  {{ base $path }}: {{ tpl ( $.Files.Get $path ) $currentScope | b64enc | quote }}
  {{- end }}
{{- end }}