{{- if .Values.source.kafka.enabled -}}
apiVersion: sources.knative.dev/{{ .Values.knative.kafkaSource.apiVersion }}
kind: KafkaSource
metadata:
  name: timescaledb
  labels:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/part-of: example-app
spec:
  consumerGroup: timescaledb

  bootstrapServers:
    - {{ include "drogue-cloud-common.kafka-bootstrap-server" . }}

  topics:
    - {{ include "drogue-cloud-common.kafka-event-topic" (dict "application" .Values.drogueApplication ) }}

  {{- include "drogue-cloud-common.knative-kafka-net" (dict "root" . "secretName" "example-kafka-secret" "userName" "example-user" ) }}

  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: timescaledb-pusher
{{- end -}}
