apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: drogue-tracing
spec:
  strategy: allInOne
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 0.5