{{- $ref := dict "root" . "name" "doppelgaenger-backend" "component" "digital-twin" "metrics" true  -}}
{{- $app := dict "root" . "name" "doppelgaenger-backend" "app" .Values.services.backend -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: doppelgaenger-backend
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"postgres"}]'
    {{- include "drogue-cloud-common.jaeger-annotations" . | nindent 4 }}
  labels:
    {{- include "drogue-cloud-twin.labels" $ref | nindent 4 }}

spec:

  replicas: {{ $app.app.deployment.replicas | default 1 }}

  selector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "drogue-cloud-twin.labels" $ref | nindent 8 }}
      annotations:
        {{- include "drogue-cloud-common.prometheus-annotations" . | nindent 8 }}
        checksum/clients: {{ include (print $.Template.BasePath "/infrastructure/sso/clients.yaml") . | sha256sum }}

    spec:
      containers:
        - name: service
          image: {{ include "drogue-cloud-common.image" $ref | quote }}
          imagePullPolicy: {{ include "drogue-cloud-common.image-pull-policy" . }}
          env:
            {{- include "drogue-cloud-common.rust.logging" $app | nindent 12 }}
            {{- include "drogue-cloud-common.jaeger-env" $app | nindent 12 }}
            {{- include "drogue-cloud-common.http-service-env" $app | nindent 12 }}
            {{- include "drogue-cloud-common.health-env" $app | nindent 12 }}
            {{- include "drogue-cloud-common.env-vars-extras" $app | nindent 12 }}

            {{- include "drogue-cloud-twin.config.common" ( dict "root" . "prefix" "" )  | nindent 12 }}
            {{- include "drogue-cloud-twin.config.service" ( dict "root" . "prefix" "SERVICE__" ) | nindent 12 }}
            {{- include "drogue-cloud-twin.config.listener" ( dict "root" . "prefix" "LISTENER__" ) | nindent 12 }}
            - name: OPENAPI_OAUTH_CLIENT
              value: api

            {{- include "drogue-cloud-common.oauth2-authenticator.env-vars" (dict "root" . "clients" (list "api" "services" )) | nindent 12 }}

          {{- include "drogue-cloud-common.health-probes" ( dict "root" . "app" $app ) | nindent 10 }}

          ports:
            {{- include "drogue-cloud-common.http-service-container-port" $app | nindent 12 }}
            {{- include "drogue-cloud-common.health-container-port" . | nindent 12 }}

          {{- include "drogue-cloud-common.container-resources" $app | nindent 10 }}

          volumeMounts:
            {{- include "drogue-cloud-common.tls-volume-mounts" $app | nindent 12 }}

      volumes:
        {{- include "drogue-cloud-common.tls-volumes" $app | nindent 8 }}
