apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client
  labels:
    {{- include "drogue-cloud-core.labels" (dict "root" . "name" "client-drogue" "component" "sso") | nindent 4 }}
spec:
  realmSelector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" (dict "root" . "name" "drogue" "component" "sso") | nindent 6 }}
  client:
    clientId: drogue
    clientAuthenticatorType: client-secret
    enabled: true
    rootUrl: ""
    publicClient: true
    implicitFlowEnabled: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    fullScopeAllowed: true
    redirectUris:
      - {{ include "drogue-cloud-common.ingress.url" (dict "root" . "prefix" "console" "ingress" .Values.services.console.ingress ) }}
      - {{ include "drogue-cloud-common.ingress.url" (dict "root" . "prefix" "console" "ingress" .Values.services.console.ingress ) }}/*
      - "http://localhost:*" {{/* used for the CLI */}}
    defaultClientScopes:
      - "email"
      - "profile"
      - "roles"
      - "web-origins"
    optionalClientScopes:
      - "address"
      - "microprofile-jwt"
      - "offline_access"
      - "phone"
    defaultRoles:
      - "drogue-user"
    protocolMappers:
      - name: add-audience
        protocol: openid-connect
        protocolMapper: oidc-audience-mapper
        consentRequired: false
        config:
          "included.client.audience": "drogue"
          "id.token.claim": "false"
          "access.token.claim": "true"
