apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client-services
  labels:
    {{- include "drogue-cloud-core.labels" (dict "root" . "name" "client-services" "component" "sso") | nindent 4 }}
spec:
  realmSelector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" (dict "root" . "name" "drogue" "component" "sso") | nindent 6 }}
  client:
    clientId: services
    clientAuthenticatorType: client-secret
    enabled: true
    publicClient: false
    implicitFlowEnabled: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
    fullScopeAllowed: true
    defaultClientScopes:
      - "email"
      - "profile"
      - "roles"
      - "web-origins"
    optionalClientScopes:
      - "address"
      - "microprofile-jwt"
      - "offline_access"
      - "phone"
    defaultRoles:
      - "drogue-user"
      - "drogue-admin"
    protocolMappers:
      - name: add-audience
        protocol: openid-connect
        protocolMapper: oidc-audience-mapper
        config:
          "included.client.audience": "services"
          "id.token.claim": "false"
          "access.token.claim": "true"
