apiVersion: v1
kind: Secret
metadata:
  name: credential-sso
  labels:
    app.kubernetes.io/part-of: sso
data:
  ADMIN_USERNAME: YWRtaW4= # admin
  ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | b64enc }}
