{{- if ne .Values.keycloak.postgres.mode "operator" }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
data:
  {{- if eq .Values.keycloak.postgres.mode "drogue" }}
  POSTGRES_DATABASE: {{ .Values.postgres.databaseName | b64enc | quote }}
  POSTGRES_EXTERNAL_ADDRESS: {{ printf "postgres.%s.svc.cluster.local." .Release.Namespace | b64enc | quote }}
  POSTGRES_EXTERNAL_PORT: {{ "5432" | b64enc | quote }}
  POSTGRES_USERNAME: {{ .Values.postgres.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  {{- else if eq .Values.keycloak.postgres.mode "external" }}
  POSTGRES_DATABASE: {{ .Values.postgres.databaseName | b64enc | quote }}
  POSTGRES_EXTERNAL_ADDRESS: {{ .Values.postgres.host | b64enc | quote }}
  POSTGRES_EXTERNAL_PORT: {{ .Values.postgres.port | default "5432" | b64enc | quote }}
  POSTGRES_USERNAME: {{ .Values.keycloak.postgres.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.keycloak.postgres.password | b64enc | quote }}
  {{- end }}
{{- end}}
