{{- $ref := dict "root" . "name" "sso" "component" "sso" -}}
{{ if eq .Values.global.cluster "openshift" }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sso
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  host: {{ include "drogue-cloud-common.ingress.host" (dict "root" . "prefix" "sso" "ingress" .Values.services.sso.ingress ) }}
  to:
    kind: Service
    name: keycloak
  port:
    targetPort: keycloak
  tls:
    termination: reencrypt
{{- else }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: keycloak
  annotations:
    {{- include "drogue-cloud-core.ingress.annotations" (dict "root" . "ingress" .Values.services.sso.ingress ) | nindent 4 }}
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  {{- include "drogue-cloud-core.ingress.className" ( dict "root" . "ingress" .Values.services.sso.ingress) | nindent 2 }}
  rules:
    - host: {{ include "drogue-cloud-common.ingress.host" (dict "root" . "prefix" "sso" "ingress" .Values.services.sso.ingress ) }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak
                port:
                  number: 8443
{{- end }}