apiVersion: v1
kind: Secret
metadata:
  name: sso-initial-admin # sso- is from the name of the instance metadata name
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4= # admin
  password: {{ .Values.keycloak.adminPassword | b64enc }}
