apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: sso
  labels:
    {{- include "drogue-cloud-core.labels" (dict "root" . "name" "keycloak" "component" "sso") | nindent 4 }}
spec:
  instances: 1
  externalAccess:
    enabled: true
    host: {{ include "drogue-cloud-common.ingress.host" (dict "root" . "prefix" "sso" "ingress" .Values.services.sso.ingress ) }}
  {{- if ne .Values.keycloak.postgres.mode "operator" }}
  externalDatabase:
    enabled: true
  {{- end }}
