---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: sso
  labels:
    {{- include "drogue-cloud-core.labels" (dict "root" . "name" "keycloak" "component" "sso") | nindent 4 }}
spec:
  instances: 1

  serverConfiguration:
    - name: db
      value: postgres
    - name: db-url-database
      secret:
        name: keycloak-db-secret
        key: database
    - name: db-url-host
      secret:
        name: keycloak-db-secret
        key: host
    - name: db-url-port
      secret:
        name: keycloak-db-secret
        key: port
    - name: db-username
      secret:
        name: keycloak-db-secret
        key: username
    - name: db-password
      secret:
        name: keycloak-db-secret
        key: password

  {{- if .Values.global.drogueCloud.keycloak.tls.enabled }}
    - name: proxy
      value: passthrough
  {{- else }}
    - name: hostname-strict-https
      value: "false"
    - name: proxy
      value: edge
  {{- end }}

  hostname: {{ include "drogue-cloud-common.ingress.host" (dict "root" . "prefix" "sso" "ingress" .Values.services.sso.ingress ) }}

  {{- if .Values.global.drogueCloud.keycloak.tls.enabled }}

  {{- if .Values.global.drogueCloud.keycloak.tls.useServiceCA }}
  tlsSecret: # FIXME: check: need to create one, or maybe not
  {{- else }}
  tlsSecret: {{ .Values.global.drogueCloud.keycloak.tls.secret }}
  {{- end }}

  {{- else }}
  tlsSecret: INSECURE-DISABLE
  {{- end }}
