apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: drogue
  labels:
    app.kubernetes.io/part-of: console
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/part-of: sso
  realm:
    realm: "drogue"
    enabled: true
    displayName: "Drogue IoT cloud"
    registrationAllowed: true
    resetPasswordAllowed: true
    loginWithEmailAllowed: false
  identityProviders: {{ .Values.keycloak.identityProviders | toYaml | nindent 4 }}
