apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: drogue
  labels:
    {{- include "drogue-cloud-core.labels" (dict "root" . "name" "drogue" "component" "sso") | nindent 4 }}
spec:
  instanceSelector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" (dict "root" . "name" "keycloak" "component" "sso") | nindent 6 }}
  realm:
    realm: "drogue"
    enabled: true
    displayName: "Drogue IoT cloud"
    registrationAllowed: true
    resetPasswordAllowed: true
    loginWithEmailAllowed: false
  identityProviders: {{ .Values.keycloak.identityProviders | toYaml | nindent 4 }}
