{{- /* Credentials for accessing the Keycloak API */}}
{{- /* By default, the same as the admin user */}}
apiVersion: v1
kind: Secret
metadata:
  name: sso-service-credentials
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4= # admin
  password: {{ .Values.keycloak.adminPassword | b64enc }}
