apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: admin
  labels:
    {{- include "drogue-cloud-core.labels" (dict "root" . "name" "admin" "component" "sso") | nindent 4 }}
spec:
  realmSelector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" (dict "root" . "name" "drogue" "component" "sso") | nindent 6 }}
  user:
    username: "admin"
    firstName: "System"
    lastName: "Admin"
    email: "user@example.com"
    enabled: true
    emailVerified: false
    credentials:
      - type: password
        value: {{ .Values.keycloak.adminPassword }}
        temporary: false
    realmRoles:
      - "offline_access"
    clientRoles:
      drogue:
        - "drogue-admin"
        - "drogue-user"
      grafana:
        - "grafana-admin"
        - "grafana-editor"
      account:
        - "manage-account"
      realm-management:
        - "manage-users"
