{{- $ref := dict "root" . "name" "ttn-operator" "component" "device-registry" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ttn-operator
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: ttn-operator
roleRef:
  kind: Role
  name: ttn-operator
  apiGroup: rbac.authorization.k8s.io
