{{- $ref := dict "root" . "name" "ttn-operator" "component" "device-registry" -}}
apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: ttn-operator
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  consumerGroup: ttn-operator
  bootstrapServers:
    - drogue-iot-kafka-bootstrap.{{ .Release.Namespace }}.svc.cluster.local.:9092
  topics:
    - registry
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: ttn-operator
