{{- if .Values.source.drogue.enabled -}}
{{- $ref := dict "root" . "name" "drogue-event-source" "component" "source" -}}
{{- $app := dict "root" . "app" .Values.source.drogue -}}

kind: Deployment
apiVersion: apps/v1
metadata:
  name: drogue-event-source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drogue-event-source
  template:
    metadata:
      labels:
        app: drogue-event-source
    spec:

      {{- include "drogue-cloud-common.pod-security-context" $app | nindent 6 }}

      containers:
        - name: drogue-event-source
          image: {{ .Values.source.drogue.image }}
          imagePullPolicy: IfNotPresent

          {{- include "drogue-cloud-common.container-security-context" $app | nindent 10 }}

          env:
            - name: RUST_LOG
              value: debug
            - name: RUST_BACKTRACE
              value: "1"

            - name: K_SINK
              value: {{ .Values.source.drogue.sink }}
            - name: MODE
              value: ws
            - name: DROGUE_ENDPOINT
              value: {{ .Values.source.drogue.endpoint }}
            - name: DROGUE_APP
              value: {{ .Values.drogueApplication.name }}
            - name: DROGUE_USER
              value: {{ .Values.source.drogue.user }}
            - name: DROGUE_TOKEN
              value: {{ .Values.source.drogue.token }}
{{- end -}}
