{{- $ref := dict "root" . "name" "post-install-keycloak" "component" "sso" -}}

{{- if .Values.keycloak.postInstall.enabled -}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: post-install-keycloak
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: post-install-keycloak
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
rules:
  - verbs:
      - create
      - update
      - get
      - patch
    apiGroups:
      - ""
    resources:
      - secrets
  - verbs:
      - patch
      - get
      - list
    apiGroups:
      - apps
    resources:
      - deployments
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: post-install-keycloak
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: post-install-keycloak
subjects:
  - kind: ServiceAccount
    name: post-install-keycloak
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: post-install-keycloak-config
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
data:
  client.json: |
    {
      "clientId": "drogue",
      "clientAuthenticatorType": "client-secret",
      "enabled": true,
      "publicClient": true,
      "implicitFlowEnabled": true,
      "standardFlowEnabled": true,
      "directAccessGrantsEnabled": false,
      "serviceAccountsEnabled": false,
      "fullScopeAllowed": true,
      "webOrigins": [
        "*"
      ],
      "defaultClientScopes": [
        "email",
        "profile",
        "roles",
        "web-origins"
      ],
      "optionalClientScopes": [
        "address",
        "microprofile-jwt",
        "offline_access",
        "phone"
      ],
      "defaultRoles": [
        "drogue-user"
      ],
      "protocolMappers": [
        {
          "name": "add-audience",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-audience-mapper",
          "config": {
            "included.client.audience": "drogue",
            "id.token.claim": "false",
            "access.token.claim": "true"
          }
        }
      ]
    }
  client-services.json: |
    {
      "clientId": "services",
      "clientAuthenticatorType": "client-secret",
      "enabled": true,
      "publicClient": false,
      "implicitFlowEnabled": false,
      "standardFlowEnabled": false,
      "directAccessGrantsEnabled": false,
      "serviceAccountsEnabled": true,
      "fullScopeAllowed": true,
      "defaultClientScopes": [
        "email",
        "profile",
        "roles",
        "web-origins"
      ],
      "optionalClientScopes": [
        "address",
        "microprofile-jwt",
        "offline_access",
        "phone"
      ],
      "defaultRoles": [
        "drogue-user",
        "drogue-admin"
      ],
      "protocolMappers": [
        {
          "name": "add-audience",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-audience-mapper",
          "config": {
            "included.client.audience": "services",
            "id.token.claim": "false",
            "access.token.claim": "true"
          }
        }
      ]
    }
---
{{- $redirect := list
  (include "drogue-cloud-common.ingress.url" (dict "root" . "prefix" "console" "ingress" .Values.services.console.ingress ))
  (printf "%s/*" (include "drogue-cloud-common.ingress.url" (dict "root" . "prefix" "console" "ingress" .Values.services.console.ingress )))
  "http://localhost:*"
-}}
{{- with (((.Values.keycloak).clients).api).extraRedirectUris }}
{{- $redirect = concat $redirect . }}
{{- end }}
kind: Job
apiVersion: batch/v1
metadata:
  name: post-install-keycloak
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
    helm.sh/hook-weight: "5"
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
      {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  backoffLimit: 1000
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: post-install-keycloak

      volumes:
        - name: init-data
          configMap:
            name: post-install-keycloak-config

      containers:
        - name: post-install
          image: {{ .Values.keycloak.postInstall.image | default .Values.global.drogueCloud.keycloak.postInstall.image }}
          imagePullPolicy: IfNotPresent

          env:
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sso-initial-admin
                  key: username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sso-initial-admin
                  key: password

            - name: KEYCLOAK_URL
              value: {{ include "drogue-cloud-common.keycloak.internal.url" . | quote }}

            - name: KCADM_PATH
              value: {{ .Values.keycloak.postInstall.kcAdmPath | default "/opt/keycloak/bin/kcadm.sh" }}

            {{- if and (not .Values.global.drogueCloud.keycloak.insecure ) .Values.global.drogueCloud.useServiceCA }}
            - name: CUSTOM_TRUSTSTORE
              value: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
            {{- end }}

            - name: REALM
              value: drogue

          volumeMounts:
            - mountPath: /etc/init-data
              name: init-data

          command:
            - bash
            - -exc
            - |

              kcadm() { local cmd="$1" ; shift ; "$KCADM_PATH" "$cmd" --config /tmp/kcadm.config "$@" ; }

              # set up trust store
              if [[ -n "${CUSTOM_TRUSTSTORE}" ]]; then
                keytool -importcert -noprompt -trustcacerts -file "${CUSTOM_TRUSTSTORE}" -keystore /tmp/truststore.jks -storepass temp1234 -storetype JKS
                kcadm config truststore /tmp/truststore.jks --trustpass temp1234
              fi

              # log in to keycloak
              kcadm config credentials config --server "$KEYCLOAK_URL" --realm master --user "$ADMIN_USERNAME" --password "$ADMIN_PASSWORD"

              # create realm
              REALM_OPTS=()
              REALM_OPTS+=(-s enabled=true)
              REALM_OPTS+=(-s "displayName=Drogue IoT")
              REALM_OPTS+=(-s registrationAllowed=true)
              REALM_OPTS+=(-s resetPasswordAllowed=true)
              REALM_OPTS+=(-s loginWithEmailAllowed=false)
              REALM_OPTS+=(-s identityProviders='{{ mustToJson .Values.keycloak.identityProviders }}')
              if kcadm get "realms/${REALM}" &> /dev/null ; then
                # exists -> update
                kcadm update "realms/${REALM}" "${REALM_OPTS[@]}"
              else
                # need to create
                kcadm create realms -s "realm=${REALM}" "${REALM_OPTS[@]}"
              fi

              # create realm roles
              kcadm create roles -r "${REALM}" -s name=drogue-user || true
              kcadm create roles -r "${REALM}" -s name=drogue-admin || true
              # add drogue-user as default role
              kcadm add-roles -r "${REALM}" --rname "default-roles-${REALM}" --rolename drogue-user

              # create clients - drogue
              ID=$(kcadm get clients -r "${REALM}" --query "clientId=drogue" --fields id --format csv --noquotes)
              CLIENT_OPTS=()
              CLIENT_OPTS+=(-s 'redirectUris={{ $redirect | toJson }}')
              CLIENT_OPTS+=(-s 'clientSecret={{ .Values.keycloak.postInstall.clients.drogue | toJson }}')
              if [[ -n "$ID" ]]; then
                # TODO: replace with update once https://github.com/keycloak/keycloak/issues/12484 is fixed
                # kcadm update "clients/${ID}" -r "${REALM}" -f /etc/init-data/client.json "${CLIENT_OPTS[@]}"
                kcadm delete "clients/${ID}" -r "${REALM}"
                kcadm create clients -r "${REALM}" -f /etc/init-data/client.json "${CLIENT_OPTS[@]}"
              else
                kcadm create clients -r "${REALM}" -f /etc/init-data/client.json "${CLIENT_OPTS[@]}"
              fi

              # client clients - services
              ID=$(kcadm get clients -r "${REALM}" --query "clientId=services" --fields id --format csv --noquotes)
              CLIENT_OPTS=()
              CLIENT_OPTS+=(-s 'clientSecret={{ .Values.keycloak.postInstall.clients.drogue | toJson }}')
              if [[ -n "$ID" ]]; then
                # TODO: replace with update once https://github.com/keycloak/keycloak/issues/12484 is fixed
                # kcadm update "clients/${ID}" -r "${REALM}" -f /etc/init-data/client-services.json "${CLIENT_OPTS[@]}"
                kcadm delete "clients/${ID}" -r "${REALM}"
                kcadm create clients -r "${REALM}" -f /etc/init-data/client-services.json "${CLIENT_OPTS[@]}"
              else
                kcadm create clients -r "${REALM}" -f /etc/init-data/client-services.json "${CLIENT_OPTS[@]}"
              fi

              # default role for service account of services
              kcadm add-roles -r "${REALM}" --uusername service-account-services --rolename drogue-admin

              {{ if .Values.keycloak.postInstall.user.enabled }}
              # create user
              ID=$(kcadm get users -r "${REALM}" --query "username={{ .Values.keycloak.postInstall.user.name }}" --fields id --format csv --noquotes)
              if [[ -n "$ID" ]]; then
                kcadm update "users/$ID" -r "${REALM}" -s enabled=true
              else
                kcadm create users -r "${REALM}" -s "username={{ .Values.keycloak.postInstall.user.name }}" -s enabled=true
              fi

              # set role
              kcadm add-roles -r "${REALM}" --uusername "{{ .Values.keycloak.postInstall.user.name }}" --rolename drogue-admin

              # set password
              ID=$(kcadm get users -r "${REALM}" --query "username={{ .Values.keycloak.postInstall.user.name }}" --fields id --format csv --noquotes)
              kcadm update "users/${ID}/reset-password" -r "${REALM}" -s type=password -s "value={{ .Values.keycloak.postInstall.user.password }}" -s temporary=false -n
              {{ end }}

{{- end -}}