{{- $ref := dict "root" . "name" "console-frontend" "component" "console" -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: console-frontend
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "drogue-cloud-core.labels" $ref | nindent 8 }}
    spec:
      containers:
        - name: endpoint
          image: {{ include "drogue-cloud-core.image-repo" . }}console-frontend:{{ include "drogue-cloud-core.image-tag" . }}
          imagePullPolicy: {{ include "drogue-cloud-core.image-pull-policy" . }}
          env:
            - name: API_URL
              value: {{ include "drogue-cloud-common.ingress.url" (dict "root" . "prefix" "api" "ingress" .Values.services.api.ingress ) }}
          ports:
            - containerPort: 8080
              name: endpoint
              protocol: TCP
          resources:
            limits:
              memory: 64Mi
          volumeMounts:
            - mountPath: /run
              name: run
            - mountPath: /endpoints
              name: endpoints
            - mountPath: /etc/config/login
              name: login-config
              readOnly: true
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 8080
              path: /
      volumes:
        - name: run
          emptyDir: {}
        - name: endpoints
          emptyDir: {}
        - name: login-config
          configMap:
            optional: true
            name: login-config
