{{- $ref := dict "root" . "name" "console-frontend" "component" "console" -}}
{{- $app := dict "root" . "name" "console-frontend" "app"  .Values.services.consoleFrontend }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: console-frontend
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}

spec:
  replicas: {{ $app.app.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "drogue-cloud-core.labels" $ref | nindent 8 }}
    spec:
      containers:
        - name: endpoint
          image: {{ include "drogue-cloud-common.image" $ref | quote }}
          imagePullPolicy: {{ include "drogue-cloud-common.image-pull-policy" . }}
          env:
            - name: API_URL
              value: {{ include "drogue-cloud-core.api.url" . | quote }}
            - name: ISSUER_URL
              value: {{ include "drogue-cloud-core.sso.issuer-url" . | quote }}
            {{- include "drogue-cloud-core.env-vars-extras" $app | nindent 12 }}

          ports:
            - containerPort: 8080
              name: service
              protocol: TCP

          {{ include "drogue-cloud-core.container-resources" $app }}

          volumeMounts:
            - mountPath: /run
              name: run
            - mountPath: /endpoints
              name: endpoints
            - mountPath: /etc/config/login
              name: login-config
              readOnly: true

          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 8080
              path: /

      volumes:
        - name: run
          emptyDir: {}
        - name: endpoints
          emptyDir: {}
        - name: login-config
          configMap:
            optional: true
            name: login-config
