{{- $ref := dict "root" . "name" "console" "component" "console" -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: console
  annotations:
    {{- include "drogue-cloud-core.ingress.annotations" (dict "root" . "app" .Values.services.console ) | nindent 4 }}
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}

spec:
  {{- include "drogue-cloud-core.ingress.className" ( dict "root" . "ingress" .Values.services.console.ingress ) | nindent 2 }}
  rules:
    - host: {{ include "drogue-cloud-core.console.host" . | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: console-api
                port:
                  name: service
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console
                port:
                  name: service
