kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: console
  annotations:
    {{ if eq .Values.global.cluster "openshift" }}
    route.openshift.io/termination: "edge"
    {{- else }}
    kubernetes.io/ingress.class: "nginx"
    {{- end }}
spec:
  rules:
    - host: {{ include "drogue-cloud-common.ingress.hostname" (list . "console" ) }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console
                port:
                  name: endpoint
