{{- $ref := dict "root" . "name" "console-backend" "component" "console" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: console-backend
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}

subjects:
  - kind: ServiceAccount
    name: console-backend

roleRef:
  kind: Role
  name: console-backend
  apiGroup: rbac.authorization.k8s.io
