{{- $ref := dict "root" . "name" "console-backend" "component" "console" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: console-backend
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}

rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "watch", "list" ]
