kind: Service
apiVersion: v1
metadata:
  name: console-backend
  labels:
    app: console-backend
spec:

  selector:
    app: console-backend

  type: ClusterIP

  ports:
    - name: endpoint
      protocol: TCP
      port: 8080
      targetPort: endpoint
