kind: Service
apiVersion: v1
metadata:
  name: console
  labels:
    app: console-frontend
spec:

  selector:
    app: console-frontend

  type: ClusterIP

  ports:
    - name: endpoint
      protocol: TCP
      port: 8080
      targetPort: endpoint
