{{- $ref := dict "root" . "name" "console-backend" "component" "console" -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: console-backend
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
