{{- $ref := dict "root" . "name" "console-backend" "component" "console" -}}
{{- $app := dict "root" . "app" .Values.services.auth -}}
kind: Service
apiVersion: v1
metadata:
  name: console-backend
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}

spec:

  selector:
    {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 4 }}

  type: ClusterIP

  ports:
    - name: service
      protocol: TCP
      port: {{ include "drogue-cloud-core.http-service-port" $app }}
      targetPort: service
