{{- $ref := dict "root" . "name" "authentication-service" "component" "device-registry" "metrics" true  -}}
{{- $app := dict "root" . "name" "authentication-service" "app" .Values.services.auth -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: authentication-service
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"postgres"}]'
    {{- include "drogue-cloud-common.jaeger-annotations" . | nindent 4 }}
  labels:
    client.oauth2.drogue.io/services: ""
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  replicas: {{ $app.app.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "drogue-cloud-core.labels" $ref | nindent 8 }}
      annotations:
        {{- include "drogue-cloud-common.prometheus-annotations" . | nindent 8 }}

    spec:
      containers:
        - name: service
          image: {{ include "drogue-cloud-common.image" $ref | quote }}
          imagePullPolicy: {{ include "drogue-cloud-common.image-pull-policy" . }}
          env:
            {{- include "drogue-cloud-common.rust.logging" $app | nindent 12 }}
            {{- include "drogue-cloud-common.jaeger-env" $app | nindent 12 }}
            {{- include "drogue-cloud-common.health-env" $app | nindent 12 }}
            {{- include "drogue-cloud-common.http-service-env" $app | nindent 12 }}
            {{- include "drogue-cloud-common.postgres.env-vars-default" . | nindent 12 }}
            {{- include "drogue-cloud-common.oauth2-authenticator.env-vars" (dict "root" . "clients" (list "services" )) | nindent 12 }}
            {{- include "drogue-cloud-common.env-vars-extras" $app | nindent 12 }}

          {{- include "drogue-cloud-common.health-probes" $app | nindent 10 }}

          ports:
            {{- include "drogue-cloud-common.http-service-container-port" $app | nindent 12 }}
            {{- include "drogue-cloud-common.health-container-port" . | nindent 12 }}

          {{- include "drogue-cloud-common.container-resources" $app | nindent 10 }}

          volumeMounts:
            {{- include "drogue-cloud-common.tls-volume-mounts" $app | nindent 12 }}

      volumes:
        - name: client-secret-services
          secret:
            secretName: keycloak-client-secret-services
        {{- include "drogue-cloud-common.tls-volumes" $app | nindent 8 }}