{{- if eq (include "drogue-cloud-core.topic-operator.type" .) "strimzi" }}
{{- $ref := dict "root" . "name" "topic-operator" "component" "device-registry" "metrics" true  -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: topic-operator
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"device-management-service"}]'
    {{- include "drogue-cloud-common.jaeger-annotations" . | nindent 4 }}
  labels:
    client.oauth2.drogue.io/services: ""
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "drogue-cloud-core.labels" $ref | nindent 8 }}
    spec:
      serviceAccountName: topic-operator
      initContainers:
        {{- include "drogue-cloud-common.init-container.wait-for-client-secret" ( dict "root" . "volume" "client-secret-services")  | nindent 8 }}
      containers:
        - name: service
          image: {{ include "drogue-cloud-common.image" (dict "root" . "name" "topic-strimzi-operator" ) | quote }}
          imagePullPolicy: {{ include "drogue-cloud-common.image-pull-policy" . }}
          env:
            {{- include "drogue-cloud-common.rust.logging" ( dict "root" . "app" .Values.services.topicOperator ) | nindent 12 }}
            {{- include "drogue-cloud-common.jaeger-env" ( dict "root" . "app" .Values.services.topicOperator ) | nindent 12 }}
            - name: HEALTH__BIND_ADDR
              value: "0.0.0.0:9090"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REGISTRY__CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_ID
            - name: REGISTRY__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_SECRET
            {{- include "drogue-cloud-core.oauth2-internal.env-vars" (dict "root" . "prefix" "REGISTRY__" ) | nindent 12 }}
            - name: CONTROLLER__TOPIC_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONTROLLER__CLUSTER_NAME
              value: drogue-iot
            - name: WORK_QUEUE__INSTANCE
              value: topic-operator
            {{- include "drogue-cloud-core.postgres.env-vars" ( dict "root" . "prefix" "WORK_QUEUE__PG__" ) | nindent 12 }}
            - name: KAFKA_SOURCE__TOPIC
              value: registry
            - name: KAFKA_SOURCE__CONSUMER_GROUP
              value: topic-operator
            - name: KAFKA_SOURCE__BOOTSTRAP_SERVERS
              value: {{ include "drogue-cloud-common.kafka-bootstrap-server" . }}
            {{- include "drogue-cloud-common.kafka-properties" (dict "root" . "prefix" "KAFKA_SOURCE__PROPERTIES__" ) | nindent 12 }}
          ports:
            {{- include "drogue-cloud-core.health-container-port" . | nindent 12 }}
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 9090
              path: /readiness
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 9090
              path: /liveness

          {{- include "drogue-cloud-core.container-resources" ( dict "root" . "app" .Values.services.topicOperator) | nindent 10 }}

      volumes:
        - name: client-secret-services
          secret:
            secretName: keycloak-client-secret-services

{{- end }}{{/* if type == "strimzi" */}}
