{{- if eq .Values.services.registry.topicOperator.type "strimzi" }}
{{- $ref := dict "root" . "name" "topic-operator" "component" "device-registry" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: topic-operator
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
rules:
  - apiGroups: [ "kafka.strimzi.io" ]
    resources: [ "kafkatopics" ]
    verbs: [ "get", "watch", "list", "create", "update", "delete", "patch" ]
  - apiGroups: [ "kafka.strimzi.io" ]
    resources: [ "kafkausers" ]
    verbs: [ "get", "watch", "list", "create", "update", "delete", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "watch", "list", "create", "update", "delete", "patch" ]
{{- end }}