name: Lint Charts

on:

  push:
    branches:
      - main
      - release-*

  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.6.3

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1
        with:
          version: v3.4.0 # ct version

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct.yaml --all
