{{- $ref := dict "root" . "name" "device-state-service" "component" "device-state" "metrics" true  -}}
{{- $app := dict "root" . "name" "device-state-service" "app" .Values.services.deviceState -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: device-state-service
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"postgres"}]'
    {{- include "drogue-cloud-common.jaeger-annotations" . | nindent 4 }}
  labels:
    client.oauth2.drogue.io/services: ""
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}

spec:
  replicas: {{ $app.app.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "drogue-cloud-core.labels" $ref | nindent 8 }}
      annotations:
        {{- include "drogue-cloud-common.prometheus-annotations" . | nindent 8 }}

    spec:
      containers:
        - name: service
          image: {{ include "drogue-cloud-common.image" $ref | quote }}
          imagePullPolicy: {{ include "drogue-cloud-common.image-pull-policy" . }}
          env:
            {{- include "drogue-cloud-common.rust.logging" $app | nindent 12 }}
            {{- include "drogue-cloud-common.jaeger-env" $app| nindent 12 }}
            {{- include "drogue-cloud-core.http-service-env" $app | nindent 12 }}
            {{- include "drogue-cloud-common.health-env" $app | nindent 12 }}
            {{- include "drogue-cloud-core.postgres.env-vars" ( dict "root" . "prefix" "SERVICE__PG__" ) | nindent 12 }}
            - name: REGISTRY__URL
              value: {{ include "drogue-cloud-core.service-url.device-management-service" . }}
            - name: REGISTRY__CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_ID
            - name: REGISTRY__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_SECRET
            {{- include "drogue-cloud-core.oauth2-internal.env-vars" (dict "root" . "prefix" "REGISTRY__" ) | nindent 12 }}
            {{- include "drogue-cloud-core.oauth2-authenticator.env-vars" (dict "root" . "clients" (list "services" )) | nindent 12 }}
            - name: INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: instance
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAFKA_DOWNSTREAM_CONFIG__BOOTSTRAP_SERVERS
              value: {{ include "drogue-cloud-common.kafka-bootstrap-server" . }}
            {{- include "drogue-cloud-common.kafka-properties" (dict "root" . "prefix" "KAFKA_DOWNSTREAM_CONFIG__PROPERTIES__" ) | nindent 12 }}
            {{- include "drogue-cloud-core.env-vars-extras" $app | nindent 12 }}

          {{- include "drogue-cloud-common.health-probes" $app | nindent 10 }}

          ports:
            {{- include "drogue-cloud-core.http-service-container-port" $app | nindent 12 }}
            {{- include "drogue-cloud-common.health-container-port" . | nindent 12 }}

          {{- include "drogue-cloud-core.container-resources" $app | nindent 10 }}

          volumeMounts:
            {{- include "drogue-cloud-core.tls-volume-mounts" $app | nindent 12 }}

      volumes:
        - name: client-secret-services
          secret:
            secretName: keycloak-client-secret-services
        {{- include "drogue-cloud-core.tls-volumes" $app | nindent 8 }}
