{{- if .Values.services.knativeOperator.enabled }}
{{- $ref := dict "root" . "name" "knative-operator" "component" "device-registry" "metrics" true  -}}
{{- $app := dict "root" . "name" "knative-operator" "app" .Values.services.knativeOperator }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: knative-operator
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"device-management-service"}]'
    client.oauth2.drogue.io/services: ""
    {{- include "drogue-cloud-common.jaeger-annotations" . | nindent 4 }}
  labels:
    {{- include "drogue-cloud-core.labels" $ref | nindent 4 }}
spec:
  replicas: {{ $app.app.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "drogue-cloud-common.selectorLabels" $ref | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "drogue-cloud-core.labels" $ref | nindent 8 }}
      annotations:
        {{- include "drogue-cloud-common.prometheus-annotations" . | nindent 8 }}

    spec:
      serviceAccountName: knative-operator
      containers:
        - name: service
          image: {{ include "drogue-cloud-common.image" $ref | quote }}
          imagePullPolicy: {{ include "drogue-cloud-common.image-pull-policy" . }}
          env:
            {{- include "drogue-cloud-common.rust.logging" $app | nindent 12 }}
            {{- include "drogue-cloud-common.jaeger-env" $app | nindent 12 }}
            {{- include "drogue-cloud-common.health-env" $app | nindent 12 }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: REGISTRY__URL
              value: {{ include "drogue-cloud-core.service-url.device-management-service" . }}
            - name: REGISTRY__CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_ID
            - name: REGISTRY__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret-services
                  key: CLIENT_SECRET
            {{- include "drogue-cloud-core.oauth2-internal.env-vars" (dict "root" . "prefix" "REGISTRY__" ) | nindent 12 }}

            - name: CONTROLLER__TARGET_NAMESPACE
              {{- with .Values.services.knativeOperator.targetNamespace }}
              value: {{ . | quote }}
              {{- else }}
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
              {{- end }}
            - name: CONTROLLER__TEMPLATE__IMAGE
              value: {{ .Values.services.knativeOperator.eventSource.image }}
            - name: CONTROLLER__KAFKA__BOOTSTRAP_SERVERS
              value: {{ include "drogue-cloud-common.kafka-bootstrap-server" . }}
            {{- include "drogue-cloud-common.kafka-properties" (dict "root" . "prefix" "CONTROLLER__KAFKA__PROPERTIES__" ) | nindent 12 }}

            - name: WORK_QUEUE__INSTANCE
              value: knative-operator
            {{- include "drogue-cloud-core.postgres.env-vars" ( dict "root" . "prefix" "WORK_QUEUE__PG__" ) | nindent 12 }}

            - name: KAFKA_SOURCE__TOPIC
              value: registry
            - name: KAFKA_SOURCE__CONSUMER_GROUP
              value: knative-operator
            - name: KAFKA_SOURCE__BOOTSTRAP_SERVERS
              value: {{ include "drogue-cloud-common.kafka-bootstrap-server" . }}
            {{- include "drogue-cloud-common.kafka-properties" (dict "root" . "prefix" "KAFKA_SOURCE__PROPERTIES__" ) | nindent 12 }}
            {{- include "drogue-cloud-core.env-vars-extras" $app | nindent 12 }}

          ports:
            {{- include "drogue-cloud-common.health-container-port" . | nindent 12 }}

          {{- include "drogue-cloud-common.health-probes" $app | nindent 10 }}

          {{- include "drogue-cloud-core.container-resources" $app | nindent 10 }}

      volumes:
        - name: client-secret-services
          secret:
            secretName: keycloak-client-secret-services

{{- end }}
